config/routes.rb
Rails.application.routes.draw do
  root to: "voter_signups#new"

  constraints subdomain: "api" do
    scope module: 'api' do
      namespace 'v1' do
        resources :rooms, only: [:create, :destroy, :index, :show] do
          resources :vote, only: [:update]
          get :next_song
          get :get_voters
        end
        resources :hosts, only: [:create]

        get '/refresher/refresh_access_token', to: 'refresher#refresh_access_token' , as: :refresh_access
      end
    end
  end

  resources :lead_signups, only: [:new, :create]
  resources :voter_signups, only: [:new, :create]

  resources :playlist, only: [:show] do
    put :suggest, on: :member
    resources :vote, only: [:update]
  end

  get :search, to: 'spotify#search'

  get '/spotify_callback', to: 'callback#spotify_callback', as: :spotify_callback
end

app/controllers/voter_signup_controller.rb
class VoterSignupController < ApplicationController
  def new
  end

  def create
    room = Room.find_by(room_code: params[:room_code])
    return redirect_to new_voter_signup_path if room.nil?

    voter = Voter.create(room: room, nickname: params[:nickname])
    session[:voter_id] = voter.id
    redirect_to playlist_path(room)
  end
end

app/controllers/voter_signups_controller.rb
class VoterSignupsController < ApplicationController
  def new
  end

  def create
    room = Room.find_by(room_code: params[:room_code])
    unless room.present?
      flash[:error] = "Ooops wrong code bruh"
      redirect_to new_voter_signup_path
      return
    end

    voter = Voter.create(room: room, nickname: params[:nickname])
    if voter.save
      session[:voter_id] = voter.id
      redirect_to playlist_path(room)
    else
      flash[:error] = voter.errors.full_messages.join(". ")
      redirect_to new_voter_signup_path
      return
    end
  end
end

app/views/voter_signups/new.html.erb
<div class="background_img">
  <div class="overlay">
      <div class="ui center aligned stackable grid">
        <div class="row">
          <div class="column">
            <img class="ui large middle aligned image amplify_logo" src="<%= asset_pack_path 'images/inverted-logo.svg' %>">
          </div>
        </div>
          <div class="row">
            <div class="column">
              <div class="ui massive normal_font white_text header">Join the party!</div>
            </div>
          </div>
        <div class="row">
          <div class="column max_width_500">
            <%= render "layouts/flash_messages" %>
            <%= form_tag(voter_signups_path, { method: :post, class: "ui form" }) do |f| %>
              <div class="field">
                <%= telephone_field_tag :room_code, nil, placeholder: "Room Code" %>
              </div>
              <div class="field">
                <%= text_field_tag :nickname, nil, placeholder: "Nickname" %>
              </div>
              <div class="field">
                <%= submit_tag "Join Room", class: "ui amplify_color_background white_text button" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

<script>
  $('.amplify_logo')
    .transition('set looping pulse')
    .transition('pulse', '1500ms')
  ;

  $('.ui.form')
    .form({
      fields: {
        room_code    : 'empty',
        nickname     : 'empty'
      },
      inline : true,
    })
  ;
</script>